version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make certificate
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t neronmoon/bullet-master-server:$CIRCLE_SHA1 .
      - run: docker push neronmoon/bullet-master-server:$CIRCLE_SHA1

      # deploy certs
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $CIRCLE_BUILD_NUM cert/*.pem
