version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t neronmoon/bullet-master-server:$CIRCLE_BUILD_NUM -t neronmoon/bullet-master-server:latest .
      - run: docker push neronmoon/bullet-master-server:$CIRCLE_BUILD_NUM
