version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Init protocol
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build image
          command: docker build -t neronmoon/bullet-master-server:master-$CIRCLE_BUILD_NUM -t neronmoon/bullet-master-server:latest .
      - run:
          name: Run tests
          command: |
            mkdir test-reports
            docker run --mount type=bind,source="$(pwd)"/test-reports,target=/srv/app/test-reports neronmoon/bullet-master-server:master-$CIRCLE_BUILD_NUM /bin/bash runtests.sh
      - store_test_results:
          path: test-reports
      - run:
          name: Push images to DockerHub
          command: |
            docker push neronmoon/bullet-master-server:master-$CIRCLE_BUILD_NUM
            docker push neronmoon/bullet-master-server:latest
  deploy:
    machine: true
    steps:
      - run:
          name: Deploy
          command: |
            ssh $BULLET_BETA_MASTER_NODE_USER@$BULLET_BETA_MASTER_NODE_HOST "python3 infrastructure/deploy_master_server.py master-$CIRCLE_BUILD_NUM" # Deploy command will be here

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
